### ISSUE TITLE
Burstiness : Continuous Metric Release Candidate

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/wg-common#101]
This issue is created to collect comments about the rolling release of "Burstiness"

This thread is for comments about the proposed metric.

This metric can be found here: https://github.com/chaoss/wg-common/blob/master/focus-areas/when/burstiness.md

See all release candidates: https://chaoss.community/metrics/

**Comment by rpaik** [comment]
Are there issues with formatting on https://chaoss.community/metric-burstiness/ (e.g. Obejectives and Implementation sections plus the 2nd paragraph under Description)?

**Comment by geekygirldawn** [comment]
@rpaik I think we fixed it - have another look :)

**Comment by rpaik** [comment]
Looks good to me 😄 Thanks @geekygirldawn!

**Comment by klumb** [comment]
Closing this issue for release
