### ISSUE TITLE
Standardize Working groups repository structure

### ISSUE THREAD

**Issue by friyaz** [chaoss/wg-common#102]
Hello everyone,

We are trying to make a standard and uniform repository structure for all working groups of CHAOSS. This will make things easier for new members. See this [document](https://docs.google.com/document/d/1chPzgJa49sO_f3wVqp_NLJupSVyKHSVyuFuwzl4m4KI/edit#) to know details about the proposed repo structure.

Please provide your feedback or concern about this proposal.

**Comment by yash2002109** [comment]
Hi @friyaz,

 I have started working on the issue. I see that this repo already follows the template, will work on other repositories.

**Comment by GeorgLink** [comment]
@friyaz , is your assessment that this issue can be closed because the Common WG fully follows the repo template?

**Comment by yash2002109** [comment]
Hi @GeorgLink,
 I found some inconsistencies in the names of images on rechecking the repo. It seems I had missed them earlier, fixed them in this   PR #112.

**Comment by GeorgLink** [comment]
I think this is complete. Thanks @yash2002109
