### ISSUE TITLE
Inconsistency in referring images

### ISSUE THREAD

**Issue by ritik-malik** [chaoss/wg-common#111]
Hi,
I saw that the images in this repository are being referred differently in different markdown files.
A good example would be the directory : [focus-areas/when](https://github.com/chaoss/wg-common/tree/master/focus-areas/when)
The following metric markdowns refer to images as:
* [Activity Dates and Times](https://github.com/chaoss/wg-common/blob/master/focus-areas/when/activity-dates-and-times.md) : HTML style - `<img src=...`
* [Burstiness](https://github.com/chaoss/wg-common/blob/master/focus-areas/when/burstiness.md) : `https://raw.githubusercontent.com/chaoss/wg-common/...`
* [Time to Close](https://github.com/chaoss/wg-common/blob/master/focus-areas/when/time-to-close.md) : `images/abc.png`
* [Time to First Response](https://github.com/chaoss/wg-common/blob/master/focus-areas/when/time-to-first-response.md) : `https://github.com/chaoss/wg-common/...`

Since there is already an attempt to bring all WG in same structure ([doc](https://docs.google.com/document/d/1chPzgJa49sO_f3wVqp_NLJupSVyKHSVyuFuwzl4m4KI/edit?pli=1#)), can we start by deciding a common way for referring the images...

Also, there is an error in mapping the metric from README, I tried to fix that in PR #109

**Comment by GeorgLink** [comment]
Thank you for spotting this inconsistency.

We want to use Markdown with relative links, like seen in `Time to Close`:

```markdown
![Average and median time to close an Issue from GrimoireLab](images/time-to-close.png)  
```

Absolute paths, full URLS, and HTML `<img>` tags should be converted

**Comment by sgoggins** [comment]
@klumb : Does using markdown relative references require a different set of actions from you than providing a full link to the http://  version of the visualization?

**Comment by germonprez** [comment]
Sounds like every WG should have an: 

'images' folder within each Focus Area

**Comment by sgoggins** [comment]
@GeorgLink Indicates using markdown relative links does not affect web deployment, and we recommend this be adopted as the standard for image referral.

**Comment by klumb** [comment]
There is some inconsistency in how this has been done. Relative paths often break on the website, however, there are instances where they have worked in the past. I haven't looked specifically at what folder/file structure works on the website site with relative path links. 

Absolute paths always work on the website.

**Comment by GeorgLink** [comment]
Relative paths for images require to start with `images/` and never with `./` -- if followed, this will work.

**Comment by GeorgLink** [comment]
The PR #112 was merged. Issue can be closed
