### ISSUE TITLE
Standard Structure for README.md in each WG repo

### ISSUE THREAD

**Issue by yash2002109** [chaoss/wg-common#116]
Hi everyone,

While standardizing the repositories, I noticed that the [README](https://github.com/chaoss/wg-common/blob/master/README.md) file of each working group has a different structure. After discussing with @GeorgLink, I have drafted a proposal for a common structure that can be implemented across these README files. I have also replicated the same as a [template](https://github.com/yash2002109/chaoss-workspace/blob/main/WG-README-template.md).

Link: https://docs.google.com/document/d/1pfipIiaemdtdiDQpvY7jOKhKzsv_3lXLLsbJiByl5GU/edit?usp=sharing

Please provide your thoughts and suggestions regarding the proposal.

**Comment by germonprez** [comment]
Yes! Thanks @yash2002109
