### ISSUE TITLE
Inconsistency in focus area goals

### ISSUE THREAD

**Issue by yash2002109** [chaoss/wg-common#123]
The goals of the focus areas are listed at

- Combined Focus Areas README -> [focus-areas/README.md](https://github.com/chaoss/wg-common/blob/master/focus-areas/README.md)
- Individual README for each Focus Area:
  -  [what/README.md](https://github.com/chaoss/wg-common/blob/master/focus-areas/what/README.md)
  - [when/README.md](https://github.com/chaoss/wg-common/blob/master/focus-areas/when/README.md)
  - [where/README.md](https://github.com/chaoss/wg-common/blob/master/focus-areas/where/README.md)
  - [who/README.md](https://github.com/chaoss/wg-common/blob/master/focus-areas/who/README.md)

**Comment by geekygirldawn** [comment]
This work has been done in the PR.
