### ISSUE TITLE
New Metric: Clones

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/wg-common#128]
This issue is related to the development of the Clones metric
https://docs.google.com/document/d/19dUCadvCciouHq6XHcnzqGjuVC3hoPGf41WqlbEFJyM/edit

**Comment by vinodkahuja** [comment]
This thread is now for collecting comments about the Clone release candidate metric. 

Metric is available at 
https://github.com/chaoss/wg-common/blob/master/focus-areas/contributions/clones.md

See all release candidates of metrics are at:
https://chaoss.community/metrics/

**Comment by klumb** [comment]
Closing for Release
