### ISSUE TITLE
Discussion on responsiveness metrics

### ISSUE THREAD

**Issue by dicortazar** [chaoss/wg-common#13]
The goal of this task is to start the discussion about the several ways we can track responsiveness metrics.

From a broader perspective, this responsiveness metrics can be seen in several of the data sources for software development.

As an example, a code review process may have several steps such as:
* the time to merge
* the time waiting for a submitter action
* the time waiting for a reviewer action
* the time for each of the iterations in a code review process
* the time to merge into master since a review is approved
* the time for approval
* the time to first response

In addition to this, we may find other measurable times at places such as in a mailing list, the first time to get an answer. Or in a more forum-based format such as Discourse or Stackoverflow where we can have the time to get an accepted answer.

With all of this in mind, and as a suggestion, we may start writing down the motivation of these metrics (mainly the goals we're following) and then start producing the specific questions and metrics.

As potential goals related to this, I have in mind a couple of them:
* Efficiency in the software development process
* Volunteers community care

**Comment by germonprez** [comment]
What is the current state of Responsiveness metrics? Not sure if there are particular metrics that are being developed.

**Comment by geekygirldawn** [comment]
Here are the docs where we are developing these metrics.

Time to first response: https://docs.google.com/document/d/1fUTQqGS1WheK01qQrtBRFBX1W_9fLfKfCHr2vIzcbAI/edit#heading=h.d6dkzltsg2wq

Time to close: https://docs.google.com/document/d/1bwCDOFr2ILss3mtCtIItteUD-ei7sjLb5EPayAmQzR4/edit?usp=sharing

**Comment by mpgjon** [comment]
A question if I may, is there yet a direction here on measuring the actual textual sentiment in responses?  (EG - natural language processing to measure positive/negative sentiment in comments?).  I understand there's something like this happening in CrossMiner and wasn't clear if that kind of measurement is completely out of scope for CHAOSS?

**Comment by GeorgLink** [comment]
Textual sentiment analysis comes up occasionally and is something CHAOSS is
interested in. The community have focused on lower hanging fruits so far
but I'm sure we are open to including a CrossMiner inspired metric for
sentiment analysis.

**Comment by klumb** [comment]
I think responsiveness and sentiment are two different metrics. Responsiveness should just focus on time. Sentiment should be built separately and a composite or collection/dashboard of responsiveness and sentiment could be discussed.

**Comment by geekygirldawn** [comment]
@dicortazar to look at the ones that aren't already included in some of our recently released metrics and add them to the release spreadsheet: https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=276406255

**Comment by GeorgLink** [comment]
Daniel added metrics to the shared metric tracking spreadsheet: 

https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit#gid=276406255

**Comment by GeorgLink** [comment]
We released the metrics 
* [Time to First Response](https://chaoss.community/metric-time-to-first-response/) and 
* [Time to Close](https://chaoss.community/metric-time-to-close/).

I suggest we create smaller issues for new metrics and close this gigantic issue.

Metrics not yet defined:
- the time to merge
- the time waiting for a submitter action
- the time waiting for a reviewer action
- the time for each of the iterations in a code review process
- the time to merge into master since a review is approved
- the time for approval

**Comment by dicortazar** [comment]
+1 to close this ticket.

As I was the one sending this, I'll proceed as follows:
* Create a new ticket for each of the previous metrics
* Create their Google doc with the template
* Close this ticket with references to those new tickets

**Comment by dicortazar** [comment]
I'm leaving out of this conversation the two last metrics of the discussion:
* the time to merge into master since a review is approved
* the time for approval

These are software delivery metrics and may be part of another discussion :).

**Comment by GeorgLink** [comment]
Thanks Daniel!
