### ISSUE TITLE
Collaboration Platform Activity

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-common#132]
This issue is created to collect comments about the rolling release of "Collaboration Platform Activity"

This thread is for comments about the proposed metric.

This metric can be found here: https://github.com/chaoss/wg-common/blob/master/focus-areas/place/collaboration-platform-activity.md

See all release candidates: https://chaoss.community/metrics/

## CHAOSS Metric Quality Checklist
This checklist is used for new and updated metrics to ensure we follow CHAOSS quality standards and processes. Below checklist items don’t have to be completed all at once: create the metric release candidate issue first and then start working on the checklist.

### Process

- [x] Create the “review issue” in the authoring WG’s repo for comments during review period and paste this template in
- [x] Create pull request to edit or add metric to WG’s repo (after checking Content Quality and Technical Requirements below)
- [x] Add the new metric or metric edit to release notes issue in working group repo
- [x] Update the [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1tAGzUiZ9jdORKCnoDQJkOU8tQsZDCZVjcWqXYOSAFmE/edit)
- [x] Create issue in [CHAOSS/Translations repository](https://github.com/chaoss/translations) to kick-off translation to other languages (please use the the translation issue template)
- [x] "Metric Candidate Release" label added to the metric release candidate issue.
- [x] Metric was added to website

**When above steps are completed:**

- [x] Announce new/updated metric on mailing list, newsletter, community Zoom call, and Twitter. This can be coordinated with the community manager.

### Content Quality

- [x] Required headings are filled in, including Questions.
- [x] Description provides context to metric
- [x] Objectives list sample uses for the metric and desired outcomes
- [x] If any, DEI uses of the metric are included Objectives
- [x] Optional headings that have no content were removed
- [x] Contributors section lists those contributors that want to be named
- [x] The name of the metric is the same in (1) metric heading, (2) metric file name, (3) focus area, (4) metrics spreadsheet, (5) “review issue”, (6) translation issue, and (7) website

### Technical Requirements

- [x] Message in the metric markdown file that the metric will be part of the next regular release is at top of page and the links are correct (this is in the [metric template](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md))
- [x] Metric file name is the full metric name and only contains lower case letters and hyphens (“-”) for spaces
- [x] Images are included using markdown and relative links (as described in the metrics template)
- [x] Images have at least one empty line above and below them
- [ ] Ensure images are placed in image folder and followed [naming convention](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md)
- [x] If new focus area is created, ensure focus area is added to wg repo readme and focus area folder readme
- [x] Within the focus area, add the metric in the table and provide the link to the metric and metric question
- [x] Ensure tables within metric are converted as image and placed in the image folder (both original MD and screenshotted PNG format) and follow the naming convention
- [x] No HTML code in the metrics markdown file

**Comment by rpaik** [comment]
I assume formatting issues will be fixed? For example, items under `aggregators` look like they could be a list. 

In addition to raw numbers (e.g. numbers of messages or people), what interests me most are things like: 

- Number of new members joining the communication platform over a period (e.g. each month) and trends over time (e.g. are new members growing month-over-month?)
- Active users over a time period (e.g. what's the ratio of active/total members on channels like Discord/Discourse/Mattermost/Slack/etc?)

Also, would it make sense to list some of the collaboration tools we're considering? It wasn't completely clear what's meant by "collaboration platforms".

Finally, how do we measure message activities in "code management platforms" (I assume GitHub, GitLab, etc.)? Are we talking about things like comments on issues/PRs?

**Comment by klumb** [comment]
Thanks @rpaik!

These comments are very helpful. We will discuss them in the next common meeting.

**Comment by eyehwan** [comment]
Hi, 
Could we add more items under the **`Aggregators`**, for example:
Identities: people as independent contributors, or represent orgnizations.

Also could we add a list of channels(categorized as code management platform, chat channels, online events hold up platform etc) to describe what `Collaboration Platform` include?
Because, different types of platform by usage purposes, aggregators would be different.

**Comment by ElizabethN** [comment]
>I assume formatting issues will be fixed? For example, items under aggregators look like they could be a list.

+1 to this; I think there are supposed to be bullets in almost every section.

Also, I noticed under the _Contributors_  section, Daniel's name is spelled incorrectly. It should be "Daniel Izquierdo"

**Comment by klumb** [comment]
Closing for Release
