### ISSUE TITLE
WG metrics and OKRs

### ISSUE THREAD

**Issue by bhack** [chaoss/wg-common#164]
Do we have a space where we could start to collect some suggestion on how to introduce some of our metrics in [OKRs](https://github.com/domenicosolazzo/awesome-okr)?

As often opensource is perceived as a "positive"  [externality](https://en.wikipedia.org/wiki/Externality) but without a specific measurable impact on OKRs all the CHAOSS efforts on metrics could really help to increase the impact on opensource software hosted by large companies (or any other kind of company that use an OKRs like approach). 

If we could a contact point (checklist, extras section in metric, etc..) between metrics and OKRs I suppose it could have a great impact.

I would also be really nice if we could enforce a subset of this measurable goals directly in the [contribution covenant](https://github.com/EthicalSource/contributor_covenant).

**Comment by bhack** [comment]
I also hope that if we could start to work in this domain we are going to also analyze how we could mitigate [Goodhart law](https://en.m.wikipedia.org/wiki/Goodhart%27s_law)/[Campbell's law](https://en.m.wikipedia.org/wiki/Campbell%27s_law) effects when converting CHAOSS metrics in targets.

**Comment by bhack** [comment]
See also:
https://arxiv.org/abs/1803.04585

https://news.ycombinator.com/item?id=17320640

**Comment by bhack** [comment]
Do you think it is better to move this in [WG-risk](https://github.com/chaoss/wg-risk)?

**Comment by germonprez** [comment]
I like the idea of the metrics models wg as this (bias concerns) could be part of the narrative that we discussion around each specific metric in a model. An example is here: https://docs.google.com/document/d/1qGxLizy5iybFsVbCqXdy1A3I8P622oiiWv7iCgCL1iI/edit?usp=sharing

**Comment by bhack** [comment]
Just to and a nice short reading:
https://towardsdatascience.com/unintended-consequences-and-goodharts-law-68d60a94705c

**Comment by bhack** [comment]
A gentle introduction to OKRs vs performance:
https://www.koan.co/blog/okrs-vs-performance-management

**Comment by germonprez** [comment]
Thanks for sharing these resources @bhack. I really think that a best approach for these is going to be inclusion in our metrics models. I'm not sure we can easily/immediately refactor all metrics.

**Comment by bhack** [comment]
@germonprez I have a related ticket in https://github.com/chaoss/wg-metrics-models/issues/17

So I don't know if you want to nove this there on just to close It here.

**Comment by germonprez** [comment]
I think if the related ticket in the MM WG is tracking the same conversation, it's okay to close this issue.
