### ISSUE TITLE
Organization Affiliation Ready for WG Feedback

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-common#17]
Please provide thoughts and comments on the following Common Metric: 

https://docs.google.com/document/d/16srWUaScABMXnFoEoKpPhNk2UndRrRvRcaO92-CTOes/edit#

@geekygirldawn @GeorgLink

**Comment by GeorgLink** [comment]
I made comments on the document. 

@alpgarcia, maybe you could help add information on where to find organizational affiliation data in GrimoireLab.

**Comment by alpgarcia** [comment]
@GeorgLink not sure if you mean at the level of specific components dealing with affiliations information or in terms of final information available.

**Comment by GeorgLink** [comment]
@alpgarcia I was thinking about the same edits we made to the Evolution WG metrics. The idea would be to add a sample visualization with description on how to create it in GrimoireLab. ... I realize that this Organizational Diversity metric can have many visualizations, but maybe we can limit ourselves to the basic pie-chart that is on the default panel.

**Comment by alpgarcia** [comment]
@GeorgLink there is a [specific dashboard for Affiliations](https://chaoss.biterg.io/app/kibana#/dashboard/Affiliations) that could help to see this in action for CHAOSS community. The goal of the dashboard is easing affiliations management. At the same time it provides a view of organizational diversity based on a pie and a table, with some extra filters to play around.

So maybe we could mention the panel and explain how to build the pie chart, as we did for Evolution WG metrics?

**Comment by GeorgLink** [comment]
Thank you @alpgarcia. I tried my hand by adding to directly into the google doc linked in the first issue. What do you think, does this address your suggestion.

**Comment by alpgarcia** [comment]
I've added a comment directly on the document trying to explain the implications of using `all_onion` instead of `affiliations`.

**Comment by GeorgLink** [comment]
Thank you @alpgarcia we should fix it according to your suggestion. Whoever has time first can pick this one up.

**Comment by geekygirldawn** [comment]
This was done for the release
