### ISSUE TITLE
Suggestion to rename a few metrics

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-common#176]
Hi all, 

There is a suggestion to change the names of the following metrics from --> to: 

[Issue Resolution Duration](https://chaoss.community/metric-issue-resolution-duration/)	to	Time to Issue Resolution
[Defect Resolution Time](https://chaoss.community/metric-defect-resolution-time/)	to Defect Resolution Duration

**Comment by ElizabethN** [comment]
These PRs were merged, so I think it's safe to close this issue.
