### ISSUE TITLE
New Metrics Being Templated (Geography)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-common#18]
Hi, 

I've started some very rough templates for the three Geography metrics at: 

https://drive.google.com/drive/folders/1XLaPM8fPQSrCle-KV4CebijW5LLd9upF?usp=sharing

These include: 
Commit Hours
Contributor Country
Contributor Employer Country

**Comment by germonprez** [comment]
Commit Hours is done but has been renamed to Activity Dates and Times

**Comment by geekygirldawn** [comment]
Tracking this in the release spreadsheet
