### ISSUE TITLE
Metric Idea: Release Frequency

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-common#183]
# Metric basics
I've been working on a [Basic Project Health Metrics Model](https://github.com/chaoss/wg-metrics-models/issues/69), and one if the metrics in that model, Release Cadence, has not yet been defined.

* **Metric title**: Release Cadence
* **Metric summary** (1-2 sentences): Determine the frequency of project releases (including point releases with bug fixes).
* **Why should this metric be created?** (1-2 sentences): In support of the Basic Project Health Metrics Model.

# Data collection and measurement

**Are there existing tools that could collect this data?** If yes, list them: Augur has a release worker to collect this data. I'm not sure about GrimoireLab, but the data is available in the GitHub API.

**If this metric involves a lot of raw data, what filters would you use to narrow down the metric?** If applicable, describe ways to filter the data into smaller segments: Type of release (major, minor, etc.), tag name, date of creation / publication, size, etc.

**How would you visualize this metric?** If you have an idea on how this metric should be visualized or displayed so it makes the most sense to a viewer, describe that here: You can see a visualization in the [metrics model](https://docs.google.com/document/d/1jBBKIEYaeI61LKjYHTnCh3a4Ih7zq6LuZA_arBmr0_M/edit)

# About you

I'll start working on this metric using the template, and we can track the progress in the Common WG meetings

**Comment by eyehwan** [comment]
@geekygirldawn , I write down something for this metric. 

**Metric summary** Determine the number of releases in the last year.
**Why should this metric be created?** The high frequency of releases indicates that software artifacts are iterating rapidly to respond to user needs. Of course, software projects belong to different industries and fields, also decided that the frequency of its iterations is not always as high as possible, for example, large platform software project release cycle is six months to a year.
**Are there existing tools that could collect this data?** [OSS-Compass](https://oss-compass.org/) could support the data:
**How would you visualize this metric?** Two open source Relational Database projects, getting from [OSS-Compass](https://oss-compass.org/)
![image](https://user-images.githubusercontent.com/1535756/211459594-ff786cfa-acd7-4056-b575-db45754f8e11.png)

**Comment by geekygirldawn** [comment]
@eyehwan - Thanks! I've started a Google doc based on the metric template and incorporated your thoughts in it as well: https://docs.google.com/document/d/1aB8Fb8q_4CtqLGlsLmF9rtb20BZ2XsEK3UZKHltX0d8/edit Please have a look, and I look forward to your suggestions :)

**Comment by sgoggins** [comment]
Augur collects GitHub release data at the repository level. I think that is a useful canonical data source for projects hosted on GitHub. I am sure Gitee and GitLab have the same kind of API's available. The only question I have is whether or not we want to account for releases that are not reflected in the Git platforms. I propose we rely on the Git platforms, though there are likely some libraries that manage releases solely using package managers. I think this choice about how to define "release" is the biggest question. Otherwise, I think the metric definition is quite close to ready.

**Comment by geekygirldawn** [comment]
@sgoggins I think what you're describing is more of an implementation detail for where you might collect the data. Since this is just the metrics definition, I think we can leave the definition of "release" open to the interpretation for a particular project, since as you mentioned, various projects publish releases in different places. But, this is important for people to think about, so I added this text to the Data Collection Strategies section:

> "In many cases, this data can be collected from the same platform as the source code (GitHub, GitLab, Gitee, etc.); however, some projects may also release code via package managers, web pages, or other locations. The data collection should align with where the project publishes their releases and makes them available to their customers."

**Comment by geekygirldawn** [comment]
Closing this Issue and replacing it with https://github.com/chaoss/wg-common/issues/184 along with the PR.
