### ISSUE TITLE
Candidate Release Comments (Organizational Diversity)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-common#22]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Organizational Diversity**

GitHub location: https://github.com/chaoss/wg-common/blob/master/focus-areas/organizational-affiliation/organizational-diversity.md

Release candidate: https://chaoss.community/metric-organizational-diversity/

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
How do you account for accurate curation of multiple email address?

**Comment by kestewart** [comment]
And individuals changing organization over time.

**Comment by foundjem** [comment]
One way to deal with this problem is to encourage a centralized account system, for example, OpenStack uses a kind of one account whereby a contributor can be identified on several login system such as Gerrit, Launchpad, Storyboard with just one login credential. 

This way, Even if persons change organization or add multiple emails, they will still be identified as one person.

**Comment by geekygirldawn** [comment]
In the strategies section, let's add the following bullet.

* Depending on the needs of the project, you may want to consider such issues as how to handle multiple email addresses, affiliation changes over time, or contractor vs. employee.

**Comment by GeorgLink** [comment]
PR to implement this change: https://github.com/chaoss/wg-common/pull/24

**Comment by germonprez** [comment]
Issued #25 in order to align better with template order.

**Comment by rpaik** [comment]
Under the "Quantitative" section, what's the difference between New Contributing Organizations (7th bullet) and New Contributor Organizations (8th bullet)?

**Comment by rpaik** [comment]
Minor edit (2nd bullet under strategies): 
"Identify contributor affiliations to get a good estimate of which organizations they belong **to**"

**Comment by sgoggins** [comment]
@geekygirldawn  and @bproffitt : Do you know what teh difference between the 7th and 8th bullets are intended to represent? 
- New Contributing Organizations (7th bullet) and 
- New Contributor Organizations (8th bullet)?

**Comment by bproffitt** [comment]
@sgoggins I believe we were differentiating between organizations that contribute as an organization and which organizations contributors belong to.

**Comment by germonprez** [comment]
Could they be written like that: 

- New organizations that contribute to the project 
- Organizations that new contributors belong to

**Comment by GeorgLink** [comment]
Ray's minor edit had been done: https://github.com/chaoss/wg-common/commit/ac5604be485ac1696394bb7f916baa0352404157#diff-a53884893cc68ad878af085699da79e9

**Comment by GeorgLink** [comment]
I'll created a new issue #27 for the remaining discussion. Closing this thread because the comment period ended.
