### ISSUE TITLE
clarifying qualitative measures

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-common#27]
This issue is a discussion that started during the review phase of the first CHAOSS metrics release.

---

> Under the "Quantitative" section, what's the difference between New Contributing Organizations (7th bullet) and New Contributor Organizations (8th bullet)?

_Originally posted by @rpaik: https://github.com/chaoss/wg-common/issues/22#issuecomment-512104939_

---

> @geekygirldawn and @bproffitt : Do you know what the difference between the 7th and 8th bullets are intended to represent?
>   * New Contributing Organizations (7th bullet) and
>   * New Contributor Organizations (8th bullet)?

_Originally posted by @sgoggins: https://github.com/chaoss/wg-common/issues/22#issuecomment-515085157_

---

> @sgoggins I believe we were differentiating between organizations that contribute as an organization and which organizations contributors belong to.

_Originally posted by @bproffitt: https://github.com/chaoss/wg-common/issues/22#issuecomment-515088877_

---

> Could they be written like that:
>   * New organizations that contribute to the project
>   * Organizations that new contributors belong to

_Originally posted by @germonprez: https://github.com/chaoss/wg-common/issues/22#issuecomment-515098095_

**Comment by geekygirldawn** [comment]
Let's go with @germonprez's suggestion of

* New organizations that contribute to the project
* Organizations that new contributors belong to
