### ISSUE TITLE
Metric Idea: Project segments by timezone

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-common#31]
Hi everyone. 

When evaluating a project, one metric could be concerned with what timezone the majority of activity occurs in. A company's ability to contribute to a project may be impacted if it is located in a timezone that is different from the project.

Taking this idea further: If a project is spread out through timezones, that is good for (geographic) diversity. However, if the work within each timezone is limited to separate areas of a project or code base, then this could be a sign that a project has disconnected parts. From this angle, the metric becomes a measure for risk.

Does this make sense?

**Comment by geekygirldawn** [comment]
This is somewhat captured in Activity Dates and Times, but we might want to add it as a filter: https://github.com/chaoss/wg-common/blob/master/focus-areas/when/activity-dates-and-times.md

Timezones are also an attribute of a person, so maybe part of a "who" metric - Contributor location.

**Comment by king-gao** [comment]
Through the meeting last night ,I found this is very interesting topic. The follow is my opinion:
If we only just look at timezone, it may not be a metric but more like a metadata, more like a user profile.

Looking at the distribution of timezone alone can show whether the contributors are diverse?

However, combining other data will have many uses. For example, if you want to know the company where the contributor is located, it is difficult to identify by email, and you can narrow the scope by time zone.

In addition, timezone can have many applications. For example, if the community wants to hold a meetup, it can accurately invite contributors.

**Comment by GeorgLink** [comment]
I believe we are covering this metric with the metrichttps://chaoss.community/metric-activity-dates-and-times/

and it's filter **Segment of a community, (e.g., GrimoireLab has more EU time zones activity and Augur more US time zones activity)**
