### ISSUE TITLE
[CMWG] List the different org affiliation metrics

### ISSUE THREAD

**Issue by tobie** [chaoss/wg-common#4]
The Common Metrics WG is going to start listing the different org affiliation (and related) metrics in [this Google doc](https://docs.google.com/document/d/1c7OD5vlESV2xDYT8nKl_qPtEmBrj2zbORMjc1xUKxL4/edit), before splitting them up into separate issues.

**Comment by GeorgLink** [comment]
Issue #6 is related

**Comment by GeorgLink** [comment]
Note, I created the pr #14 based on the table we have in the google doc. This is of course not the final version, but it helps get the work we have done already out in front of people.

**Next step:** pick one of the metrics, create a metric detail page based on one of the templates

**Comment by geekygirldawn** [comment]
This was done in the release
