### ISSUE TITLE
Release Candidate Comments (Activity Dates and Times)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-common#41]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Activity Dates and Times**

GitHub location: https://github.com/chaoss/wg-common/blob/master/focus-areas/when/activity-dates-and-times.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by klumb** [comment]
Add links to GrimoireLab and Augur in Tools Heading

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by geekygirldawn** [comment]
@sgoggins What's the best link to use for this? Can we link directly to a description of where this metrics can be found in the API Endpoint?

@GeorgLink @dicortazar Same question for you for GrimoireLab.

**Comment by GeorgLink** [comment]
Maybe just link to GrimoireLab website: https://chaoss.github.io/grimoirelab/

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
