### ISSUE TITLE
Release Candidate Comments (Contributors)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-common#43]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Contributors**

GitHub location: https://github.com/chaoss/wg-common/blob/master/focus-areas/who/contributors.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by klumb** [comment]
Add links to Grimoire Lab and Augur in Tools heading.

**Comment by bproffitt** [comment]
Add a line in the Description that elaborates how this metric gets from identifying individual contributors to determining their type. This seems to be inferred by the rest of the metric, but not explicitly stated.

**Comment by klumb** [comment]
Interview question needs to be rewritten for clarity:

"Interview question: Who do you see are the most important contributors in this project?"

"Most important" is odd choice of wording and doesn't get at the information we need.
I believe the question is trying to assess if there are contributors that are not showing up in trace data activity.

**Comment by germonprez** [comment]
Drop the image below: 

Summary number of contributors

**Comment by geekygirldawn** [comment]
@GeorgLink @dicortazar What's the best GrimoireLab link to use for this metric?

**Comment by klumb** [comment]
The augur link in the tools section is giving a 403 error.

**Comment by GeorgLink** [comment]
Depending on what the goal is:

1. The generic GrimoireLab homepage that we often link to: https://chaoss.github.io/grimoirelab/
2. The panel about contributors: https://chaoss.github.io/grimoirelab-sigils/panels/contributors-growth/

**Comment by geekygirldawn** [comment]
Case issue in:

Matrix survey item: How often do you engage in the following activities in the project?

Should be Column headings ...

**Comment by germonprez** [comment]
Replace: 

Interview question: Who do you see are the most important contributors in this project?

With: 

Interview question: Which contributors do not typically appear in lists of contributors? Which contributors is often overlooked as important contributors because their contributions are more “behind the scenes”?

**Comment by jmertic** [comment]
Again on tools - one area where LF Analytics does have a visualization for that captures across commits, issues reported, mailing lists, and Slack communication.

https://lfanalytics.io/projects/0093a1b7-e14d-42f4-8eb1-127b609ed933/dashboard

Happy to do a PR if y'all feel it fits in...

**Comment by germonprez** [comment]
Description: 

Delete first sentence 
Add new second sentence: This metric ensures that all types of contributions are fully recognized in the project.

**Comment by germonprez** [comment]
Include the visualization from: 

https://lfanalytics.io/projects/0093a1b7-e14d-42f4-8eb1-127b609ed933/dashboard

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
