### ISSUE TITLE
Release Candidate Comments(Organizational Diversity)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-common#44]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Organizational Diversity**

GitHub location: https://github.com/chaoss/wg-common/blob/master/focus-areas/who/organizational-diversity.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
"Resources" should be "References"

**Comment by geekygirldawn** [comment]
@germonprez @klumb can one of you review and merge the pull request with this change?

**Comment by germonprez** [comment]
done

**Comment by jmertic** [comment]
Not sure if this is helpful/useful at this point, but the LF Analytics offering does seem to handle this as well if we want to list more tools...

https://lfanalytics.io/projects/6030a580-1768-4df4-b4c4-3e16175d4abc/dashboard

**Comment by germonprez** [comment]
@jmertic the visualizations are not currently up. When these are up, could you include them for Organizational Diversity and Contributors -- and issue the corresponding PRs?

**Comment by jmertic** [comment]
See https://github.com/chaoss/wg-common/pull/50

**Comment by geekygirldawn** [comment]
I've merged the pull request from @jmertic to add the visualization.

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
