### ISSUE TITLE
New metric: Geographic Coverage

### ISSUE THREAD

**Issue by agallo70** [chaoss/wg-common#5]
It would be interesting to track the geographic location of the committers to an open source project. If they are all from the very same region / location, the project is pretty localized - is this a successfully adopted project? if from all over the world, would it be a more successful one?

Discussing with Jesus while in Sonoma, he suggested looking at the time zone from the commits in the git repository. It is already available from GrimoireLab and useful as is. If possible to detaile it in terms of country rather than timezone, it would be even better- e.g. Italy or France or South Africa are all in the same time zone.

**Comment by geekygirldawn** [comment]
Closed because it's templeted in #18
