### ISSUE TITLE
Common Metrics Release Notes

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-common#60]
This issue was created to capture the continuous release notes. Insight from comments will be used to create the regular release note.

Example comments could be:

- name of new metric and date of release
- descriptions of changes to existing metric 
- Changes to focus areas or restructuring of WG

**Comment by klumb** [comment]
**New Metric**
Types of Contributions
https://github.com/chaoss/wg-common/blob/master/focus-areas/what/types-of-contributions.md
Comment Period Issue #56 
Releasing to website April 21st, 2020

**Comment by germonprez** [comment]
Thanks! I was just going to do this :)

**Comment by geekygirldawn** [comment]
Note: Do not close this issue until the regular release hits. Continue to add release notes here for every continuous release metrics.

**Comment by klumb** [comment]
New Metric 
Time to Close
https://github.com/chaoss/wg-common/blob/master/focus-areas/when/time-to-close.md
Comment Period Issue #63 
Releasing to website: (KL will add date)

**Comment by GeorgLink** [comment]
Time to Release -- we want to add a Augur screenshot (to be done)

**Comment by GeorgLink** [comment]
**Common WG**
New metrics include:
- Types of Contributions 
- Time to Close
- Contributor Location

**Comment by germonprez** [comment]
Types of Contributions is released under CMC too.

**Comment by sgoggins** [comment]
Review Period ends July 31, 2020 Now.

**Comment by geekygirldawn** [comment]
Reviewed https://chaoss.community/release-history/ and it looks good for this release.

**Comment by klumb** [comment]
Release 2020-08
