### ISSUE TITLE
Release Candidate Comments (Time to Close)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-common#63]
This issue provides a platform for feedback on the Types of Contributions metric as part of the Continuous Metric Contribution. Feedback period will end May 31, 2020. If no feedback is provided, we will consider this metric ready for release.

The candidate metric can be found here: https://github.com/chaoss/wg-common/blob/master/focus-areas/when/time-to-close.md

**Comment by germonprez** [comment]
@klumb the review window has closed on this. Could you issue a PR and I'll merge it?

**Comment by geekygirldawn** [comment]
This was one of the continuous metric contribution (CMC) metrics.
