### ISSUE TITLE
Release Candidate Comments (Contributor Location)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-common#71]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Contributor Location

GitHub location: https://github.com/chaoss/wg-common/blob/master/focus-areas/who/contributor-location.md

**Comment by mbbroberg** [comment]
I really like the visualizations in this metric and the clarity of the filters. LGTM :ship:

**Comment by geekygirldawn** [comment]
No comments, so we'll use this one as-is.
