### ISSUE TITLE
Release Candidate Comments (Time to First Response)

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-common#76]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Contributor Location

https://github.com/chaoss/wg-common/blob/master/focus-areas/when/time-to-first-response.md

**Comment by klumb** [comment]
This will be on release 202101

**Comment by geekygirldawn** [comment]
Decided that since it was just adding visualizations and not changing any metrics definitions that it was ok to do for a released metric.
