### ISSUE TITLE
Release Notes - 2021-02

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-common#82]
This issue was created to capture the continuous contribution notes. Insight from comments will be used to create the regular release notes.

Example comments could be:

name of new metric and date of release
descriptions of changes to existing metric
Changes to focus areas or restructuring of WG

**Comment by klumb** [comment]
New metric - Technical Forks

**Comment by germonprez** [comment]
New Metric - Review cycle Duration within change request

**Comment by klumb** [comment]
New metric Burstiness

**Comment by klumb** [comment]
Closing for Release 2021-03
