### ISSUE TITLE
The link of "Holder" metric redirects no where

### ISSUE THREAD

**Issue by jaskiratsingh2000** [chaoss/wg-common#83]
## Problem:

The link of the "**[Holder](https://github.com/chaoss/wg-common/tree/master/focus-areas/where)**" metric inside the "Where" Focus areas redirects nowhere.

**Comment by GeorgLink** [comment]
Could be that “Holder” is short for “Placeholder”, indicating that we don’t have a metric yet.

We should remove it.

**Comment by GeorgLink** [comment]
Resolved. Thanks @jaskiratsingh2000
