### ISSUE TITLE
New metric: Time to Merge

### ISSUE THREAD

**Issue by dicortazar** [chaoss/wg-common#86]
This ticket comes from a broader discussion related to [responsiveness metrics](https://github.com/chaoss/wg-common/issues/13). 

This ticket aims at discussing the **Time to Merge** metric.

Google Doc is available at https://docs.google.com/document/d/1HAJMNtKEGMdnwtA_dp-vaX-GjbA6bvbrwYdSJNEfdEQ/edit?usp=sharing

**Comment by vinodkahuja** [comment]
We are currently working on this and the discussion is happening in the google doc.

**Comment by geekygirldawn** [comment]
Closing because time to merge should really be a filter on Time to Close.
