### ISSUE TITLE
New Metric: Review Cycle Duration within a Change Request

### ISSUE THREAD

**Issue by dicortazar** [chaoss/wg-common#89]
This ticket comes from a broader discussion related to [responsiveness metrics](https://github.com/chaoss/wg-common/issues/13). 

This ticket aims at discussing the **Time between Review Cycles** metric.

Google doc is available at https://docs.google.com/document/d/1-86OoosdSKSthe1_K5WrlECy3j2AqdKwJEK2doF3YBU/edit?usp=sharing

**Comment by vinodkahuja** [comment]
We are currently working on this and the discussion is happening in the google doc.

**Comment by dicortazar** [comment]
Just did some sanity check on the doc and went through all the suggestions. Thanks a lot!

**Comment by GeorgLink** [comment]
We revised the text today and clarified the nature of the metric. Need to review again next time and then it should be ready for public review.

**Comment by geekygirldawn** [comment]
Changed the title of this issue to be consistent with the new title of the metric after discussing it in the Common Metrics WG.

**Comment by ElizabethN** [comment]
Merged with PR #97
