### ISSUE TITLE
Review Cycle Duration within a Change Request : Continuous Metric Release Candidate

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/wg-common#98]
This issue is created to collect comments about the rolling release of "Review Cycle Duration within a Change Request"

This thread is for comments about the proposed metric.

The metric can be found here: https://github.com/chaoss/wg-common/pull/97

See all release candidates: https://chaoss.community/metrics/

**Comment by klumb** [comment]
Closing this for release
